(()=>{'use strict';
const API='https://script.google.com/macros/s/AKfycbyIcTsXxu896spK_ZSZnyciyw-XMw6_JLPx9oAjJugVdnUnonYQn5OrJvcT1MNY5ZI9/exec';
const CLIENT_ID='94430402616-5bhfnaric11em723f6pccmct6raqga2r.apps.googleusercontent.com';
const CREATOR='ljbooks3@gmail.com';
const SCOPE='https://www.googleapis.com/auth/drive';
const FOLDER='My Reels';
let reels=[],loading=false,token=null,oauth=null,authPromise=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const setStatus=s=>{const e=$('status');if(e)e.textContent=s};
function setAccount(email){$('account').textContent=email||'';$('login').textContent=email?'Signed in':'Sign in'}
function waitForGoogle(timeout=8000){return new Promise((resolve,reject)=>{const started=Date.now();(function check(){if(window.google?.accounts?.oauth2)return resolve();if(Date.now()-started>timeout)return reject(Error('Google sign-in could not load. Check your internet connection or disable extensions that block Google sign-in.'));setTimeout(check,100)})()})}
function initOAuth(){if(oauth)return oauth;oauth=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,callback:()=>{}});return oauth}
async function getToken(){if(token)return token;if(authPromise)return authPromise;authPromise=(async()=>{await waitForGoogle();const c=initOAuth();return new Promise((resolve,reject)=>{let done=false;const previous=c.callback;c.callback=r=>{c.callback=previous;if(done)return;done=true;if(r?.error){reject(Error(r.error_description||r.error));return}if(!r?.access_token){reject(Error('Google did not return an access token.'));return}resolve(r.access_token)};try{c.requestAccessToken({prompt:'select_account'})}catch(e){done=true;c.callback=previous;reject(e)}setTimeout(()=>{if(!done){done=true;c.callback=previous;reject(Error('Google sign-in timed out.'))}},20000)})})().finally(()=>{authPromise=null});return authPromise}
async function signIn(){const b=$('login');b.disabled=true;setStatus('Opening Google sign-in…');try{const t=await getToken();token=t;const r=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:'Bearer '+t}});if(!r.ok)throw Error('Google account check failed.');const u=await r.json();const email=String(u.email||'').toLowerCase();if(email!==CREATOR.toLowerCase()){token=null;throw Error('Please use the creator Google account.')}setAccount(email);setStatus('Signed in.');}catch(e){token=null;setAccount('');setStatus(e.message||'Sign-in failed.')}finally{b.disabled=false}}
function listPublic(){if(loading)return;loading=true;const b=$('refresh');b.disabled=true;setStatus('Refreshing…');const cb='myReels_'+Date.now();const script=document.createElement('script');let done=false;const finish=()=>{if(done)return;done=true;loading=false;delete window[cb];script.remove();b.disabled=false};window[cb]=data=>{try{if(!data?.ok)throw Error(data?.error||'Could not read the video library.');reels=Array.isArray(data.reels)?data.reels:[];render();setStatus(reels.length+' videos • Google Drive');}catch(e){console.error(e);setStatus(e.message||'Could not load the library.')}finally{finish()}};script.onerror=()=>{setStatus('Could not reach the video library. Tap Refresh to try again.');finish()};script.src=API+'?action=list&callback='+cb+'&t='+Date.now();document.head.appendChild(script);setTimeout(()=>{if(!done){setStatus('Refresh timed out. Tap Refresh to try again.');finish()}},15000)}
function render(){const grid=$('grid');$('count').textContent=reels.length;if(!reels.length){grid.innerHTML='<div class="empty">No videos found in the My Reels Google Drive folder.</div>';return}grid.innerHTML=reels.map((x,i)=>`<article class="card" data-index="${i}"><div class="thumb">${x.thumbnail?`<img loading="lazy" src="${esc(x.thumbnail)}" alt="${esc(x.name||'Reel')}">`:'<div class="noImage">▶</div>'}<span class="play">▶</span></div><div class="cardBody"><b class="title">${esc(x.name||'Reel')}</b><small class="meta">${x.instagram?'@'+esc(String(x.instagram).replace(/^@+/,'')):'Video '+(i+1)}</small></div></article>`).join('');grid.querySelectorAll('.card').forEach(c=>c.onclick=()=>openViewer(reels[Number(c.dataset.index)]))}
function openViewer(x){if(!x?.id)return;const viewer=$('viewer'),player=$('player');$('viewerTitle').textContent=x.name||'Reel';player.src='https://drive.google.com/file/'+encodeURIComponent(x.id)+'/preview';viewer.classList.add('show');viewer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeViewer(){const viewer=$('viewer'),player=$('player');player.src='about:blank';viewer.classList.remove('show');viewer.setAttribute('aria-hidden','true');document.body.style.overflow=''}
async function driveJson(url,options={}){if(!token)throw Error('Please sign in first.');let r=await fetch(url,{...options,headers:{...(options.headers||{}),Authorization:'Bearer '+token}});if(r.status===401){token=null;setAccount('');throw Error('Google sign-in expired. Please sign in again.')}if(!r.ok){let msg='Google Drive error '+r.status;try{const j=await r.json();msg=j.error?.message||msg}catch{}throw Error(msg)}return r.json()}
async function findFolder(){const q="mimeType='application/vnd.google-apps.folder' and name='"+FOLDER+"' and trashed=false";const j=await driveJson('https://www.googleapis.com/drive/v3/files?q='+encodeURIComponent(q)+'&spaces=drive&fields=files(id,name)&pageSize=20');if(j.files?.[0])return j.files[0];return driveJson('https://www.googleapis.com/drive/v3/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:FOLDER,mimeType:'application/vnd.google-apps.folder'})})}
async function uploadResumable(blob,name,parent,onProgress){const meta={name,mimeType:blob.type||'video/mp4',parents:[parent],description:'MY_REELS_META:'+JSON.stringify({name:name.replace(/\.[^.]+$/,''),instagram:String($('instagram').value||'').trim().replace(/^@+/,'')})};const start=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&fields=id,name,mimeType,createdTime',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','X-Upload-Content-Type':blob.type||'video/mp4','X-Upload-Content-Length':String(blob.size)},body:JSON.stringify(meta)});if(!start.ok)throw Error('Could not start the Drive upload.');const location=start.headers.get('Location');if(!location)throw Error('Google Drive did not return an upload URL.');return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',location);xhr.setRequestHeader('Content-Type',blob.type||'video/mp4');xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(e.loaded/e.total)};xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300){try{resolve(JSON.parse(xhr.responseText))}catch{resolve({})}}else reject(Error('Drive upload failed ('+xhr.status+').'))};xhr.onerror=()=>reject(Error('Upload connection failed.'));xhr.send(blob)})}
async function upload(){const file=$('videoFile').files[0];if(!file)return;const btn=$('startUpload');btn.disabled=true;$('uploadMessage').textContent='Signing in…';try{if(!token){token=await getToken();const u=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json());if(String(u.email||'').toLowerCase()!==CREATOR.toLowerCase())throw Error('Please use the creator Google account.');setAccount(u.email)}const folder=await findFolder();$('uploadMessage').textContent='Uploading to Google Drive…';const title=String($('title').value||'').trim();const safe=(title||file.name.replace(/\.[^.]+$/,'')).replace(/[\\/:*?"<>|]/g,' ').trim()||'Reel';const ext=(file.name.match(/\.[^.]+$/)||['.mp4'])[0];await uploadResumable(file,safe+ext,folder.id,p=>$('uploadBar').style.width=Math.round(p*100)+'%');$('uploadBar').style.width='100%';$('uploadMessage').textContent='Uploaded. Refreshing…';setTimeout(()=>{closeUpload();listPublic()},500)}catch(e){console.error(e);$('uploadMessage').textContent=e.message||'Upload failed.'}finally{btn.disabled=false}}
function openUpload(){resetUpload();$('uploadModal').classList.add('show');$('uploadModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';if(!token)setStatus('Sign in when you upload a reel.')}
function closeUpload(){if(!$('uploadModal').classList.contains('show'))return;$('uploadModal').classList.remove('show');$('uploadModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function resetUpload(){$('videoFile').value='';$('title').value='';$('instagram').value='';$('uploadBar').style.width='0%';$('uploadMessage').textContent='';$('startUpload').textContent='Choose a video first';$('startUpload').disabled=true}
function fileChanged(){const f=$('videoFile').files[0];$('startUpload').disabled=!f;$('startUpload').textContent=f?'Upload to Google Drive':'Choose a video first'}
document.addEventListener('DOMContentLoaded',()=>{setAccount('');$('login').onclick=signIn;$('refresh').onclick=listPublic;$('upload').onclick=openUpload;$('close').onclick=closeViewer;$('cancelUpload').onclick=closeUpload;$('videoFile').onchange=fileChanged;$('startUpload').onclick=upload;$('viewer').addEventListener('click',e=>{if(e.target===$('viewer'))closeViewer()});$('uploadModal').addEventListener('click',e=>{if(e.target===$('uploadModal'))closeUpload()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeViewer();closeUpload()}});listPublic()});
})();
