(()=>{'use strict';
const CLIENT_ID='94430402616-5bhfnaric11em723f6pccmct6raqga2r.apps.googleusercontent.com';
const ALLOWED=(window.MY_REELS_CREATOR_EMAIL||'ljbooks3@gmail.com').toLowerCase();
const $=id=>document.getElementById(id);
function showLogin(){document.body.innerHTML=`<main style="min-height:100vh;display:grid;place-items:center;background:#09070d;color:#fff;font-family:system-ui;padding:24px"><section style="width:min(440px,100%);padding:32px;border:1px solid #ffffff18;border-radius:24px;background:#121019;text-align:center;box-shadow:0 25px 80px #0008"><div style="font-size:42px">🔐</div><h1>Creator Login</h1><p style="color:#aaa">Only the authorized My Reels creator account can access upload and Google Drive tools.</p><button id="creatorLogin" style="border:0;border-radius:12px;padding:13px 18px;background:#fff;color:#111;font-weight:800;cursor:pointer">Continue with Google</button><p id="gateMsg" style="color:#ff8fb8"></p><a href="./" style="color:#bbb">← Public library</a></section></main>`;$('creatorLogin').onclick=login}
function login(){if(!window.google?.accounts?.oauth2){$('gateMsg').textContent='Google sign-in is still loading. Try again.';return}const c=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:'openid email profile',callback:async r=>{if(r.error){$('gateMsg').textContent=r.error_description||r.error;return}try{const u=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:'Bearer '+r.access_token}}).then(x=>x.json());if(String(u.email||'').toLowerCase()!==ALLOWED){$('gateMsg').textContent='This Google account is not authorized as the creator.';return}sessionStorage.setItem('myReelsCreatorEmail',u.email);loadCreator()}catch(e){$('gateMsg').textContent='Could not verify the Google account.'}}});c.requestAccessToken({prompt:'consent'})}
function loadCreator(){document.body.innerHTML='<div id="app"></div>';['app.js','metadata-sync.js','list-remote.js','remote-drive.js'].forEach((src,i)=>{const s=document.createElement('script');s.src='./'+src+'?v=creator2';document.body.appendChild(s)})}
window.addEventListener('DOMContentLoaded',showLogin);
})();
