(()=>{'use strict';
const CLIENT_ID='94430402616-5bhfnaric11em723f6pccmct6raqga2r.apps.googleusercontent.com';
const ALLOWED=(window.MY_REELS_CREATOR_EMAIL||'ljbooks3@gmail.com').toLowerCase();
const DRIVE_SCOPE='https://www.googleapis.com/auth/drive';
const SESSION='myReelsCreatorSession';
const $=id=>document.getElementById(id);
function session(){try{return JSON.parse(sessionStorage.getItem(SESSION)||'null')}catch{return null}}
function showLogin(){document.body.innerHTML=`<main style="min-height:100dvh;display:grid;place-items:center;background:#0a0a0b;color:#fff;font-family:system-ui,-apple-system,sans-serif;padding:20px"><section style="width:min(420px,100%);padding:30px;border:1px solid #28282b;border-radius:20px;background:#111113;text-align:center"><div style="width:52px;height:52px;margin:auto;border-radius:14px;display:grid;place-items:center;background:#1c1c20;font-weight:800">MR</div><h1 style="margin:18px 0 8px">Creator Login</h1><p style="color:#999;line-height:1.5;margin:0 0 22px">Sign in once to manage your private My Reels library.</p><button id="creatorLogin" style="border:0;border-radius:11px;padding:12px 18px;background:#fff;color:#111;font-weight:750;cursor:pointer">Continue with Google</button><p id="gateMsg" style="min-height:20px;color:#ff8fa8"></p><a href="./" style="color:#999">Back to public library</a></section></main>`;$('creatorLogin').onclick=login}
function login(){if(!window.google?.accounts?.oauth2){$('gateMsg').textContent='Google sign-in is still loading. Try again.';return}const c=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:'openid email profile '+DRIVE_SCOPE,callback:async r=>{if(r.error){$('gateMsg').textContent=r.error_description||r.error;return}try{const u=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:'Bearer '+r.access_token}}).then(x=>x.json());if(String(u.email||'').toLowerCase()!==ALLOWED){$('gateMsg').textContent='This Google account is not authorized.';return}const expires=Date.now()+(Number(r.expires_in||3600)*1000);sessionStorage.setItem(SESSION,JSON.stringify({email:u.email,token:r.access_token,expires}));sessionStorage.setItem('myReelsCreatorEmail',u.email);loadCreator()}catch(e){$('gateMsg').textContent='Could not verify the Google account.'}}});c.requestAccessToken({prompt:'consent'})}
function loadCreator(){document.body.innerHTML='<div id="app"></div>';['app.js','metadata-sync.js','list-remote.js','remote-drive.js','player-fix.js'].forEach((src,i)=>{const s=document.createElement('script');s.src='./'+src+'?v=creator4';s.onload=()=>{};document.body.appendChild(s)})}
function boot(){const s=session();if(s?.email?.toLowerCase()===ALLOWED){loadCreator();return}showLogin()}
window.addEventListener('DOMContentLoaded',boot);
})();
