(()=>{'use strict';
const API='https://script.google.com/macros/s/AKfycbyIcTsXxu896spK_ZSZnyciyw-XMw6_JLPx9oAjJugVdnUnonYQn5OrJvcT1MNY5ZI9/exec';
const $=id=>document.getElementById(id); let reels=[],loading=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ig=s=>{s=String(s||'').trim().replace(/^@+/,'');return s?'https://www.instagram.com/'+encodeURIComponent(s)+'/':''};
function render(){const box=$('library');if(!box)return;box.innerHTML=reels.length?reels.map((x,i)=>`<article class="card"><button class="thumb" data-play="${i}">${x.thumbnail?`<img loading="lazy" src="${esc(x.thumbnail)}" alt="">`:''}<span class="play">▶</span></button><div class="ct"><b>${esc(x.name||'Reel')}</b>${x.instagram?`<a href="${esc(ig(x.instagram))}" target="_blank" rel="noopener">@${esc(String(x.instagram).replace(/^@+/,''))}</a>`:''}</div></article>`).join(''):'<div class="empty">No reels published yet.</div>';const n=$('statTotal');if(n)n.textContent=reels.length;box.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>play(reels[Number(b.dataset.play)]));}
function setStatus(s){const x=$('publicStatus');if(x)x.textContent=s}
function refresh(){if(loading)return;loading=true;const btn=$('refresh');if(btn)btn.disabled=true;setStatus('Loading reels…');const cb='myReels_'+Date.now();const script=document.createElement('script');let finished=false;const finish=()=>{if(finished)return;finished=true;loading=false;script.remove();delete window[cb];if(btn)btn.disabled=false};window[cb]=j=>{try{if(!j||!j.ok)throw Error(j?.error||'Could not load reels');reels=Array.isArray(j.reels)?j.reels:[];render();setStatus(reels.length+' reels');}catch(e){console.error(e);setStatus('Could not load reels. Tap Refresh.')}finally{finish()}};script.onerror=()=>{setStatus('Could not connect to video library. Tap Refresh.');finish()};script.src=API+'?action=list&callback='+cb+'&ts='+Date.now();document.head.appendChild(script);setTimeout(()=>{if(!finished){setStatus('Loading timed out. Tap Refresh.');finish()}},15000)}
function play(x){const viewer=$('publicViewer'),video=$('publicVideo');if(!viewer||!video||!x?.video)return;$('publicTitle').textContent=x.name||'Reel';const a=$('publicIg');a.style.display=x.instagram?'inline-flex':'none';if(x.instagram)a.onclick=()=>window.open(ig(x.instagram),'_blank','noopener');video.src=x.video;viewer.classList.add('show');video.play().catch(()=>{})}
function close(){const video=$('publicVideo');video.pause();video.removeAttribute('src');video.load();$('publicViewer').classList.remove('show')}
function boot(){if(!$('publicLibrary'))return;$('refresh').onclick=refresh;$('publicBack').onclick=close;refresh()}
document.addEventListener('DOMContentLoaded',boot);window.MyReelsPublic={refresh};
})();
