(()=>{'use strict';
const CATALOG='./public-catalog.json?v='+Date.now();
const CREATOR='ljbooks3@gmail.com';
let catalog=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const insta=s=>{s=String(s||'').trim().replace(/^@+/,'');return s?'https://www.instagram.com/'+encodeURIComponent(s)+'/':''};
async function load(){const r=await fetch(CATALOG,{cache:'no-store'});if(!r.ok)throw Error('Catalogue unavailable');const j=await r.json();catalog=Array.isArray(j)?j:(j.videos||[]);render();}
function render(){let root=document.getElementById('publicMode');if(!root){root=document.createElement('div');root.id='publicMode';document.body.appendChild(root)}root.innerHTML=`<div class="public-wrap"><header class="public-top"><div><b>My Reels</b><span>Hijabi Girls Who Slay</span></div><button id="publicRefresh">↻ Refresh</button><button id="creatorLogin">Creator Login</button></header><section class="public-hero"><div class="eyebrow">MY REELS</div><h1>Hijabi Girls <em>Who Slay In Hijab</em></h1><p>Dance • Photoshoots • Style • Beautiful moments.</p></section><main><div class="public-head"><div><h2>All Reels</h2><small>${catalog.length} videos</small></div><input id="publicSearch" placeholder="Search reels…"></div><div id="publicGrid" class="public-grid"></div></main><div id="publicViewer" class="public-viewer" hidden><button id="publicClose">← Back</button><b id="publicTitle"></b><a id="publicIg" target="_blank" rel="noopener">Instagram</a><video id="publicVideo" controls playsinline preload="metadata"></video></div></div>`;draw();document.getElementById('publicRefresh').onclick=()=>load().catch(()=>{});document.getElementById('publicSearch').oninput=e=>draw(e.target.value);document.getElementById('creatorLogin').onclick=()=>location.hash='#creator';document.getElementById('publicClose').onclick=()=>close();}
function draw(q=''){const grid=document.getElementById('publicGrid');if(!grid)return;const term=q.toLowerCase().trim();const list=catalog.filter(x=>!term||String(x.name||'').toLowerCase().includes(term)||String(x.insta||'').toLowerCase().includes(term));grid.innerHTML=list.map((x,i)=>`<article class="public-card" data-i="${catalog.indexOf(x)}"><div class="public-thumb">${x.thumbnailUrl?`<img src="${esc(x.thumbnailUrl)}" loading="lazy">`:'<span>▶</span>'}</div><h3>${esc(x.name||'Reel '+(i+1))}</h3>${x.insta?`<a href="${esc(insta(x.insta))}" target="_blank" rel="noopener">@${esc(String(x.insta).replace(/^@/,''))}</a>`:''}</article>`).join('')||'<div class="empty">No reels published yet.</div>';grid.querySelectorAll('.public-card').forEach(c=>c.onclick=e=>{if(e.target.closest('a'))return;open(catalog[Number(c.dataset.i)])})}
async function open(x){const v=document.getElementById('publicViewer'),vid=document.getElementById('publicVideo');v.hidden=false;document.getElementById('publicTitle').textContent=x.name||'Reel';const a=document.getElementById('publicIg');if(x.insta){a.href=insta(x.insta);a.hidden=false}else a.hidden=true;vid.src=x.videoUrl;await vid.play().catch(()=>{});}
function close(){const v=document.getElementById('publicViewer'),vid=document.getElementById('publicVideo');vid.pause();vid.removeAttribute('src');vid.load();v.hidden=true}
function creatorGate(){const h=location.hash==='#creator';const pub=document.getElementById('publicMode');if(pub)pub.style.display=h?'none':'block';document.querySelector('.app')?.style.setProperty('display',h?'':'none');document.querySelector('.mobile')?.style.setProperty('display',h?'':'none');if(h&&!window.__creatorLoaded){window.__creatorLoaded=true;document.dispatchEvent(new Event('myreels:creator'))}}
window.addEventListener('hashchange',creatorGate);window.addEventListener('load',()=>{load().catch(()=>render());creatorGate()});
})();