(()=>{'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let reels=[], currentUrl='';
function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),3500)}
function instaUrl(s){s=String(s||'').trim().replace(/^@+/,'').replace(/\s+/g,'');return s?'https://www.instagram.com/'+encodeURIComponent(s)+'/':''}
function render(){const q=String($('search').value||'').toLowerCase().trim();const list=reels.filter(r=>!q||[r.name,r.instagram,r.caption].join(' ').toLowerCase().includes(q));$('count').textContent=reels.length;$('library').innerHTML=list.map((r,i)=>`<article class="card" data-i="${reels.indexOf(r)}"><div class="thumb"><img loading="lazy" src="${esc(r.thumbnail)}" alt=""><button class="play">▶</button></div><div class="ct"><h3>${esc(r.name||'Reel '+(i+1))}</h3>${r.instagram?`<a class="ig" href="${esc(instaUrl(r.instagram))}" target="_blank" rel="noopener">@${esc(String(r.instagram).replace(/^@/,''))}</a>`:''}</div></article>`).join('')||`<div class="empty">No reels found.</div>`;$('library').querySelectorAll('.card').forEach(c=>c.onclick=()=>open(+c.dataset.i))}
function open(i){const r=reels[i];if(!r)return;currentUrl=r.video;$('viewerTitle').textContent=r.name||'Reel';$('viewer').classList.add('show');const v=$('video');v.src=r.video;v.load();$('ig').style.display=r.instagram?'inline-flex':'none';$('ig').onclick=()=>window.open(instaUrl(r.instagram),'_blank','noopener');v.play().catch(()=>{});}
function close(){const v=$('video');v.pause();v.removeAttribute('src');v.load();$('viewer').classList.remove('show');currentUrl=''}
async function refresh(){const api=window.MY_REELS_PUBLIC_API;if(!api||api.includes('__APPS_SCRIPT_URL__')){toast('Public catalogue is not configured yet.');return}$('refresh').disabled=true;$('refresh').textContent='Refreshing…';try{const r=await fetch(api+'?action=list&t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Catalogue HTTP '+r.status);const j=await r.json();if(!j.ok)throw Error(j.error||'Catalogue failed');reels=Array.isArray(j.reels)?j.reels:[];render();$('updated').textContent='Updated '+new Date(j.updatedAt||Date.now()).toLocaleString();}catch(e){toast(e.message)}finally{$('refresh').disabled=false;$('refresh').textContent='↻ Refresh'}}
window.addEventListener('DOMContentLoaded',()=>{render();$('refresh').onclick=refresh;$('search').oninput=render;$('close').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});refresh()});
})();
