(()=>{'use strict';
const CREATOR='ljbooks3@gmail.com';
const CATALOG='./public-catalog.json';
const $=s=>document.querySelector(s);
let data=[];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function card(x,i){const name=x.name||`Reel ${i+1}`;const ig=String(x.instagram||'').replace(/^@+/,'');const thumb=x.thumbnail||'';return `<article class="card public-card" data-id="${esc(x.id||'')}" data-video="${esc(x.video||'')}" data-title="${esc(name)}"><div class="thumb">${thumb?`<img loading="lazy" src="${esc(thumb)}" alt="${esc(name)}">`:''}<div class="remote-play">▶</div></div><div class="cardbody"><b>${esc(name)}</b>${ig?`<small>@${esc(ig)}</small>`:''}</div></article>`}
function render(){const g=$('#library');if(!g)return;g.innerHTML=data.map(card).join('')||'<div class="empty">No reels available.</div>';g.querySelectorAll('.public-card').forEach(c=>c.onclick=()=>play(c.dataset.video,c.dataset.title,c.dataset.id));const n=$('#topSub');if(n)n.textContent=data.length+' videos';const t=$('#statTotal');if(t)t.textContent=data.length}
function play(url,title,id){if(!url)return;const v=$('#viewer');if(!v)return;const old=v.querySelector('.public-view-video');if(old){old.pause();old.remove()}const vid=document.createElement('video');vid.className='public-view-video';vid.controls=true;vid.playsInline=true;vid.preload='metadata';vid.src=url;vid.style.cssText='width:100%;height:calc(100vh - 110px);object-fit:contain;background:#000;border-radius:16px';v.appendChild(vid);if($('#viewerTitle'))$('#viewerTitle').textContent=title;if($('#ig')){const x=data.find(a=>String(a.id)===String(id));const ig=String(x?.instagram||'').replace(/^@+/,'');$('#ig').style.display=ig?'inline-block':'none';if(ig)$('#ig').onclick=()=>window.open('https://www.instagram.com/'+encodeURIComponent(ig)+'/','_blank','noopener')};v.classList.add('show');vid.play().catch(()=>{})}
async function refresh(){try{const r=await fetch(CATALOG+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Catalogue unavailable');data=await r.json();render()}catch(e){console.warn(e)}}
function creator(){const b=$('#creatorLogin');if(!b)return;b.onclick=()=>{const email=prompt('Creator email');if(String(email||'').trim().toLowerCase()===CREATOR){sessionStorage.setItem('myreels_creator','1');location.reload()}else alert('Creator access denied.')}}
function boot(){creator();const b=$('#publicRefresh');if(b)b.onclick=refresh;refresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();