(()=>{'use strict';
const CLIENT_ID='94430402616-5bhfnaric11em723f6pccmct6raqga2r.apps.googleusercontent.com';
const SCOPE='https://www.googleapis.com/auth/drive';
const DB='private_reels_v3',STORE='reels',FOLDER='My Reels';
let client=null,token=null,authPromise=null,busy=false,lastIds='';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function init(){if(client||!window.google?.accounts?.oauth2)return !!client;client=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,callback:r=>{if(r.error){authPromise?.reject?.(Error(r.error_description||r.error));authPromise=null;return}token=r.access_token;authPromise?.resolve?.(token);authPromise=null}});return true}
function auth(user=false){if(token)return Promise.resolve(token);if(!init())return Promise.reject(Error('Google authorization is unavailable'));if(authPromise)return authPromise.promise;let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});authPromise={promise,resolve,reject};try{client.requestAccessToken({prompt:user?'consent':''})}catch(e){authPromise=null;reject(e)}setTimeout(()=>{if(authPromise?.promise===promise){authPromise=null;reject(Error('Google authorization timed out'))}},12000);return promise}
async function api(url,opt={}){if(!token)await auth(false);let r=await fetch(url,{...opt,headers:{...(opt.headers||{}),Authorization:'Bearer '+token}});if(r.status===401){token=null;await auth(false);r=await fetch(url,{...opt,headers:{...(opt.headers||{}),Authorization:'Bearer '+token}})}if(!r.ok){let m='HTTP '+r.status;try{m=(await r.json()).error?.message||m}catch{}throw Error(m)}return r}
async function json(url,opt){return(await api(url,opt)).json()}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB);r.onsuccess=e=>res(e.target.result);r.onerror=()=>rej(r.error)})}
async function localAll(){const d=await openDB();return new Promise((res,rej)=>{const q=d.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
async function localPut(x){const d=await openDB();return new Promise((res,rej)=>{const q=d.transaction(STORE,'readwrite').objectStore(STORE).put(x);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
async function digest(blob){const h=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer());return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function folder(){const q=encodeURIComponent("mimeType='application/vnd.google-apps.folder' and name='"+FOLDER+"' and trashed=false");const j=await json('https://www.googleapis.com/drive/v3/files?q='+q+'&spaces=drive&fields=files(id,name)&pageSize=100');if(j.files?.[0])return j.files[0].id;return (await json('https://www.googleapis.com/drive/v3/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:FOLDER,mimeType:'application/vnd.google-apps.folder'})})).id}
async function driveList(){const id=await folder(),q=encodeURIComponent("'"+id+"' in parents and trashed=false");let out=[],page='';do{let u='https://www.googleapis.com/drive/v3/files?q='+q+'&spaces=drive&fields=nextPageToken,files(id,name,mimeType,size,description,appProperties,thumbnailLink,createdTime,modifiedTime)&pageSize=1000';if(page)u+='&pageToken='+encodeURIComponent(page);const j=await json(u);out.push(...(j.files||[]));page=j.nextPageToken||''}while(page);return{id,files:out}}
function hashOf(f){return f.appProperties?.sha256||String(f.name||'').match(/(?:reel|cover)[-_]([a-f0-9]{64})/i)?.[1]||''}
async function upload(blob,meta,parent){const boundary='----MyReelsAuto'+Date.now()+Math.random().toString(16).slice(2);const mime=meta.mime||blob.type||'video/mp4';const body=new Blob(['--'+boundary+'\r\nContent-Type: application/json\r\n\r\n',JSON.stringify({name:meta.name,mimeType:mime,parents:[parent],appProperties:{kind:'video',sha256:meta.sha256},description:meta.desc||''}),'\r\n--'+boundary+'\r\nContent-Type: '+mime+'\r\n\r\n',blob,'\r\n--'+boundary+'--\r\n']);const r=await api('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,appProperties,thumbnailLink',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});return r.json()}
async function autoBackup(userGesture=false){if(busy)return;busy=true;try{const local=await localAll();const candidates=[];for(const x of local){if(!(x.video instanceof Blob)||!x.video.size)continue;if(!x.sha256)x.sha256=await digest(x.video);candidates.push(x)}if(!candidates.length)return;let D;try{D=await driveList()}catch(e){if(userGesture){await auth(true);D=await driveList()}else throw e}const existing=new Map();for(const f of D.files){const h=hashOf(f);if(h&&f.mimeType?.startsWith('video/'))existing.set(h,f)}let uploaded=0;for(const x of candidates){let f=existing.get(x.sha256);if(!f){f=await upload(x.video,{name:'reel-'+x.sha256+'.mp4',sha256:x.sha256,mime:x.mime,desc:x.desc||x.caption||''},D.id);existing.set(x.sha256,f);uploaded++}if(x.driveFileId!==f.id||!x.backedUp){x.driveFileId=f.id;x.backedUp=true;await localPut(x)}}if(userGesture)notify(uploaded?'✓ Backup complete — '+uploaded+' new video uploaded':'✓ Already backed up — no duplicate upload')}catch(e){if(userGesture)notify('Backup waiting: '+e.message)}finally{busy=false}}
function notify(s){const t=$('#toast');if(t){t.textContent=s;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),3500)}}
function driveVideoUrl(id){return 'https://drive.google.com/file/d/'+encodeURIComponent(id)+'/preview'}
async function refreshRemote(userGesture=false){if(busy)return;busy=true;try{notify('Refreshing from Google Drive…');const D=await driveList();const videos=D.files.filter(f=>f.mimeType?.startsWith('video/'));const sig=videos.map(f=>f.id).sort().join('|');if(sig===lastIds&&!userGesture){busy=false;return}lastIds=sig;const local=await localAll();const byHash=new Map(local.map(x=>[x.sha256,x]));const grid=$('#library');if(!grid)return;grid.innerHTML=videos.map((f,i)=>{const h=hashOf(f),x=byHash.get(h),name=x?.name||x?.title||f.name.replace(/^reel-[a-f0-9]{64}\./,'').replace(/\.[^.]+$/,'')||('Reel '+(i+1));return `<article class="card remote-card" data-drive-id="${esc(f.id)}"><div class="thumb remote-thumb"><div class="remote-play">▶</div></div><div class="cardbody"><b>${esc(name)}</b><small>☁ Google Drive • view online</small></div></article>`}).join('')||'<div class="empty">No reels found in Google Drive.</div>';grid.querySelectorAll('.remote-card').forEach(c=>c.onclick=()=>openViewer(c.dataset.driveId,c.querySelector('b')?.textContent||'Reel'));const top=$('#topSub');if(top)top.textContent=videos.length+' videos • Google Drive';notify('✓ Refreshed — '+videos.length+' videos from Drive')}catch(e){notify('Refresh failed: '+e.message)}finally{busy=false}}
function openViewer(id,title){const v=$('#viewer');if(!v)return;const vid=$('#vid');if(vid){vid.removeAttribute('src');vid.style.display='none'}const old=v.querySelector('.drive-frame');if(old)old.remove();const frame=document.createElement('iframe');frame.className='drive-frame';frame.src=driveVideoUrl(id);frame.allow='autoplay; fullscreen';frame.allowFullscreen=true;frame.style.cssText='width:100%;height:calc(100vh - 110px);border:0;border-radius:16px;background:#000';v.appendChild(frame);if($('#viewerTitle'))$('#viewerTitle').textContent=title;v.classList.add('show')}
function addRefreshButtons(){const a=$('#syncTop');if(a){a.textContent='↻ Refresh';a.id='refreshTop';a.onclick=()=>refreshRemote(true)}const b=$('#sync');if(b){b.textContent='↻ Refresh';b.id='refreshDrive';b.onclick=()=>refreshRemote(true)}const p=document.querySelector('.actions');if(p&&!document.querySelector('#autoLabel')){const s=document.createElement('span');s.id='autoLabel';s.textContent='Auto backup ON';s.style.cssText='font-size:12px;color:#b7a9c8;margin-right:8px';p.prepend(s)}}
function hookSave(){const b=$('#saveBtn');if(b&&!b.dataset.autoHook){b.dataset.autoHook='1';b.addEventListener('click',()=>{auth(false).catch(()=>{});setTimeout(()=>{autoBackup(true);setTimeout(()=>refreshRemote(true),2500)},1800)},{capture:true})}}
function boot(){addRefreshButtons();hookSave();refreshRemote(false);setInterval(()=>{hookSave();autoBackup(false)},5000);setInterval(()=>refreshRemote(false),15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1000));else setTimeout(boot,1000);
})();