(()=>{
'use strict';
const q=id=>document.getElementById(id);
const say=s=>typeof toast==='function'&&toast(s);
const prog=(d,t,s)=>typeof progress==='function'?progress(d,t,s):(q('progressBox')?.classList.add('show'),q('progressBar')&&(q('progressBar').style.width=(t?Math.round(d/t*100):0)+'%'),q('progressText')&&(q('progressText').textContent=s+' • '+d+'/'+t));
function hashFromFile(f){const p=f.appProperties||{};if(p.sha256)return p.sha256;const m=String(f.name||'').match(/(?:reel-|video-|cover-|__)([a-f0-9]{64})(?:\.[^.]+)?$/i);return m?m[1]:''}
async function allDriveFiles(){
 const fq="mimeType='application/vnd.google-apps.folder' and name='My Reels' and trashed=false";
 const fr=await driveFetch('https://www.googleapis.com/drive/v3/files?q='+encodeURIComponent(fq)+'&fields=files(id,name)&pageSize=100');
 if(!fr.ok)throw Error('Drive folder lookup failed ('+fr.status+')');
 const folders=(await fr.json()).files||[];
 if(!folders.length){await ensureFolder();return await driveList()}
 const out=[];
 for(const folder of folders){let page='';do{let u='https://www.googleapis.com/drive/v3/files?q='+encodeURIComponent("'"+folder.id+"' in parents and trashed=false")+'&fields=nextPageToken,files(id,name,mimeType,size,modifiedTime,description,appProperties,md5Checksum)&pageSize=1000';if(page)u+='&pageToken='+encodeURIComponent(page);const r=await driveFetch(u,{cache:'no-store'});if(!r.ok)throw Error('Drive file listing failed ('+r.status+')');const j=await r.json();out.push(...(j.files||[]));page=j.nextPageToken||''}while(page)}
 return out;
}
async function remoteIndex(files){
 const videos=new Map(),covers=new Map(),deleted=new Set();
 const unknown=files.filter(f=>f.mimeType?.startsWith('video/')&&!hashFromFile(f));
 for(let i=0;i<unknown.length;i++){const f=unknown[i];prog(i,Math.max(1,unknown.length),'Identifying existing Drive video');try{const h=await sha(await driveDownload(f.id,'video/mp4'));f.appProperties={...(f.appProperties||{}),sha256:h,kind:'reel'};await driveFetch('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(f.id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({appProperties:f.appProperties})})}catch(e){console.warn('Cannot fingerprint',f.name,e)}}
 for(const f of files){const p=f.appProperties||{},h=hashFromFile(f);if(p.kind==='deleted'||f.name.startsWith('deleted-')){if(h)deleted.add(h);continue}if(!h)continue;if(p.kind==='cover'||f.mimeType?.startsWith('image/')){if(!covers.has(h))covers.set(h,f);continue}if(f.mimeType?.startsWith('video/')||p.kind==='reel'){if(!videos.has(h))videos.set(h,[]);videos.get(h).push(f)}}
 return {videos,covers,deleted};
}
async function syncV7(){
 if(syncBusy)return say('Sync already running…');if(!accessToken){connect();return}syncBusy=true;q('syncBtn')&&(q('syncBtn').disabled=true);q('syncTop')&&(q('syncTop').disabled=true);q('progressBox')?.classList.add('show');if(typeof setDrive==='function')setDrive(true,'Syncing…');
 try{let locals=await all();const by=new Map();for(const x of locals){if(!x.video||!x.video.size)continue;if(!x.sha256)x.sha256=await sha(x.video);if(!by.has(x.sha256))by.set(x.sha256,x);else await remove(x.id)}locals=[...by.values()];prog(0,Math.max(1,locals.length+1),'Reading local library');let files=await allDriveFiles();let idx=await remoteIndex(files);const remoteCount=[...idx.videos.values()].reduce((n,a)=>n+a.length,0),total=Math.max(1,locals.length+remoteCount+idx.deleted.size);let done=0;
  for(const h of idx.deleted){const local=by.get(h);if(local){await remove(local.id);by.delete(h)}for(const f of idx.videos.get(h)||[])await driveDelete(f.id);const c=idx.covers.get(h);if(c)await driveDelete(c.id);done++;prog(done,total,'Applying deletions')}
  for(const [h,arr] of idx.videos){if(idx.deleted.has(h))continue;for(let i=1;i<arr.length;i++)await driveDelete(arr[i].id);if(arr.length)idx.videos.set(h,[arr[0]])}
  for(const x of [...by.values()]){if(idx.deleted.has(x.sha256))continue;let f=idx.videos.get(x.sha256)?.[0];if(!f){f=await driveUpload(x.video,'reel-'+x.sha256+'.mp4',x.mime||x.video.type||'video/mp4',{sha256:x.sha256,kind:'reel',title:String(x.name||'Reel').slice(0,120),instaId:String(x.instaId||''),created:String(x.created||Date.now())},x.desc||'');idx.videos.set(x.sha256,[f])}else{try{await driveFetch('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(f.id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({appProperties:{...(f.appProperties||{}),sha256:x.sha256,kind:'reel',title:String(x.name||'Reel').slice(0,120),instaId:String(x.instaId||''),created:String(x.created||Date.now())},description:x.desc||''})})}catch(e){console.warn(e)}}x.driveFileId=f.id;let c=idx.covers.get(x.sha256);if(!c&&x.cover){c=await driveUpload(x.cover,'cover-'+x.sha256+'.jpg','image/jpeg',{sha256:x.sha256,kind:'cover'},'Thumbnail for '+(x.name||'Reel'));idx.covers.set(x.sha256,c)}x.driveCoverId=c?.id||null;await put(x);done++;prog(done,total,'Backing up '+(x.name||'Reel'))}
  files=await allDriveFiles();idx=await remoteIndex(files);const current=await all(),localHashes=new Set(current.map(x=>x.sha256)),incoming=[...idx.videos.entries()].filter(([h])=>!idx.deleted.has(h)&&!localHashes.has(h));for(let i=0;i<incoming.length;i++){const [h,arr]=incoming[i],f=arr[0],p=f.appProperties||{};prog(i+1,Math.max(1,incoming.length),'Downloading '+(i+1)+' of '+incoming.length+' new reels');const video=await driveDownload(f.id,'video/mp4'),cf=idx.covers.get(h),cover=cf?await driveDownload(cf.id,'image/jpeg'):await makeCover(video);await add({name:p.title||String(f.name).replace(/^reel-/,'').replace(/\.mp4$/i,''),desc:f.description||'',instaId:p.instaId||'',video,cover,created:Number(p.created)||Date.now(),mime:'video/mp4',sha256:h,driveFileId:f.id,driveCoverId:cf?.id||null})}
  await render();await listRender();if(typeof setDrive==='function')setDrive(true,'Connected • Synced just now');q('storageStatus')&&(q('storageStatus').textContent='Connected');q('statStatus')&&(q('statStatus').textContent='Online');prog(1,1,'Sync complete');say('☁️ Sync complete — existing videos matched, new videos only');setTimeout(()=>q('progressBox')?.classList.remove('show'),1400);
 }catch(e){console.error('sync-v7',e);q('driveStatus')&&(q('driveStatus').textContent='Connected • Sync error');q('progressText')&&(q('progressText').textContent='Sync failed: '+(e?.message||e));say('Sync failed: '+(e?.message||e))}finally{syncBusy=false;q('syncBtn')&&(q('syncBtn').disabled=false);q('syncTop')&&(q('syncTop').disabled=false)}}
function install(){const b=q('syncBtn'),t=q('syncTop');if(b){b.onclick=syncV7;b.dataset.syncFix='v7'}if(t){t.onclick=()=>{if(typeof showScreen==='function')showScreen('settingsScreen');syncV7()};t.dataset.syncFix='v7'}}
let n=0;const timer=setInterval(()=>{install();if(++n>80)clearInterval(timer)},250);install();
})();